### PR TITLE
fixes #291

### LINKED ISSUE #291: Value's returning 'NULL_VALUE' for all fields as well as other data types
Previously if `Value.nullValue` was equal to `"NULL_VALUE"` then the `Value` was null, however since version 4.0.0 all my firestore documents field values have `nullValue == "NULL_VALUE"` in addition to their correct values such as a `integerValue` or `mapValue`

### PR DESCRIPTION
**Pull request by torbenkeller**
This should fix #291

### CODE REVIEW

**Comment by kevmoo** [comment]
Please revert the JSON download. I Just want to see the dart file changes!

**Comment by torbenkeller** [comment]
@googlebot I signed it!

**Comment by kevmoo** [comment]
You need to run the other script in `tool/` from the root.

**Comment by torbenkeller** [comment]
@kevmoo which script do you mean?

**Comment by kevmoo** [comment]
Looking solid! Need to add an entry to the changelogs, too!

**Comment by torbenkeller** [comment]
Seems like because I incremented the package version the documentation links point to not existing websites. Should I decrement it again?

**Comment by kevmoo** [comment]
> Seems like because I incremented the package version the documentation links point to not existing websites. Should I decrement it again?

Nope. It's the doc generator failing. I'm going to run a couple of tests locally then I'll land.

This is AWESOME work. Thank you!

**Comment by torbenkeller** [comment]
Thank you for the fast merge and kind Feedback!

**Comment by kevmoo** [comment]
`5.0.1` is now published!

**Pull request merged**
