### PR TITLE
[googleapis_auth] Add support for non-Google OAuth providers

### PR DESCRIPTION
**Pull request by bryanoltman**
This change allows consumers of this package to provide their own authorization and token endpoints for use with non-Google OAuth providers.

This is accomplished through the introduction of an `AuthEndpoints` class, which has properties for these two URIs. There is a single concrete subclass of `AuthEndpoints` in this package for the Google values (`GoogleAuthEndpoints`). Consumers wishing to support other providers should subclass `AuthEndpoints` and provide the appropriate URIs for the provider they wish to support.

Most of the exported APIs now accept an `AuthEndpoints` parameter whose default value is `GoogleAuthEndpoints`.

This change should be non-breaking and transparent to existing users. 

Fixes https://github.com/google/googleapis.dart/issues/596

Note: there are some added tests in `auth_code_test.dart` that aren't directly relevant to this PR. They were added in Shorebird's fork to satisfy our coverage checks. Happy to remove them to make this PR cleaner/more focused.

### CODE REVIEW

**Comment by kevmoo** [comment]
How 'bout a changelog entry?

**Comment by bryanoltman** [comment]
Done. Wasn't sure about versioning, but a minor bump seemed appropriate.

**Comment by kevmoo** [comment]
published!

**Comment by bryanoltman** [comment]
Awesome! Thanks for the help and quick attention

**Pull request merged**
